### ISSUE TITLE
Challenge Participant Admin Interface

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#128]
Create a Wagtail interface that will allow content managers to review Challenge submissions, shortlist finalists and assign winners.

### Tasks

- Add boolean flag fields to Challenge Participant/Entry for content interface (`is_read`, `is_shortlisted`, `is_winner`)
- Create Participant/Entry Views for challenge types
- The content managers must be able to tick the flags from the list view

### Questions

When the winner flag is ticked, is the winning state immediately available to the client app?

### Discussions

- Should the View list Participants or Entries?
- How does the app know the user is a winner? Is the app going to poll the server, or does it check the winner state each time `MainActivity` is opened?

1 Days

**Comment by ChadGarrett** [comment]
Added flags for is_read, is_shortlisted and is_winner.

Participant admin interface is implemented, with checkboxes to mark is read, shortlisted and winner.

Challenge screen updated so that a user can navigate from a challenge to the participants for that challenge.

Needs discussion for how to notify users, related issue #455
