### ISSUE TITLE
Tips: Search magnifier faulty

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#228]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 06 Tips 03
UX Flow: Tips_

**Issue:**
Magifier search button doesn't work, Button doesn't return the results.
**Date:** 04/12/2016

**Comment by ReinhardtCromhout** [comment]
@Lashes08 When testing this issue I could not replicate the problem. Is this happening on all possible search terms or only some of them? Because currently the app does not provide feedback when a search term is entered that there are no results for and thus it may look like the app is not responding.

**Comment by wvictor-rr** [comment]
@Lashes08 Better user feedback was added. Please retest.
