### ISSUE TITLE
Bot: Coversational UI sometimes gets populated with stale data (Add/Edit Goal)

### ISSUE THREAD

**Issue by ReinhardtCromhout** [praekeltfoundation/gem-bbb-indo#499]
This may be an issue in other places but it has been observed in add/edit goal conversations.

2 Hours (Investigation, fix and testing)

**Comment by wvictor-rr** [comment]
@ReinhardtCromhout Didn't we fix this by copying the nodes retrieved from the bot feed?

**Comment by ReinhardtCromhout** [comment]
@wvictor-rr Copying the nodes retrieved from the bot feed solved the problem in some cases, so I left that solution in, but I noticed that this did not solve the problem in all cases.

**Comment by ReinhardtCromhout** [comment]
@wvictor-rr Just an update, I could not replicate this issue when adding a goal but I could replicated it when editing a goal. I will investigate why this happens.

**Comment by wvictor-rr** [comment]
@ReinhardtCromhout I think this is because user input during Goal edit is not applied to the Goal object during the conversation, but the text view holder populates its strings from the Goal object.

So, the `TextViewHolder` is populated using `GoalBotController.resolveParam`, which draws its values from the `GoalBotController.goal` field. The latest user input is only inserted during `GoalEditController.doUpdate`, which happens later.

We can't change the Goal directly on user input as there are nodes that ask the user to confirm their input. For instance `goal_edit_target_confirm`. We would have to handle he user cancelling out of their input.
